kumuluzee:
  cors:
    filters:
      - url-pattern: /*  # This will apply CORS to all your endpoints
        allow-origin: "*"  # This will allow all origins
        allow-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD  # Allowed methods
        allow-headers: Authorization, Content-Type  # Allowed headers
        expose-headers: ""  # Headers that are exposed to the client
        max-age: 15  # Maximum age (in seconds) of the CORS preflight request
        allow-credentials: false  # Whether  cookies are allowed
  openapi-mp:
    extension: true
    version: "3.0.1"
    servlet:
      mapping: /comments/api-specs/*
    ui:
      enabled: true
      mapping: /comments/api-specs/ui
      specification-server: http://20.231.233.217/comments/api-specs
      server-auto-config:
        enabled: true
        original-uri-check: false
  logs:
    config-file:
      '<?xml version="1.0" encoding="UTF-8"?>
       <Configuration name="tutorial-logging">
         <Appenders>
           <!-- Added Console Appender -->
           <Console name="console" target="SYSTEM_OUT">
             <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
           </Console>
           <!-- Existing Socket Appender -->
           <Socket name="logstash" protocol="tcp" host="20.246.243.191" port="5043">
             <JsonLayout compact="true" eventEol="true">
               <!-- Add this KeyValuePair to distinguish the microservice -->
               <KeyValuePair key="serviceName" value="comment-service"/>
             </JsonLayout>
           </Socket>
         </Appenders>
         <Loggers>
           <!-- Default logger -->
           <Root level="info">
             <AppenderRef ref="console"/>
             <AppenderRef ref="logstash"/>
           </Root>
         </Loggers>
       </Configuration>'
  name: comment-service
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8081
  discovery:
    etcd:
      hosts: http://etcd-client:2379
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 90000
    etcd:
      hosts: http://etcd-client:2379
  health:
    servlet:
      mapping: /comments/health
      enabled: true
    logs:
      enabled:  true
      type: both
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 100000000
      etcd-health-check:
        connection-url: http://etcd-client:2379/health
      http-health-check:
        connection-url: https://github.com/metodija747/MicroserviceMasterProductComments.git
  metrics:
    servlet:
      enabled: true
      mapping: /comments/metrics
  jwt-auth:
    jwks-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw/.well-known/jwks.json
    issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw
  opentracing:
    jaeger:
      service-name: comment-service
      agent-host: simplest-agent.observability
      agent-port: 5775
      reporter:
        log-spans: true
        max-queue-size: 10000
        flush-interval: 1000
        tags: key1=val1, key2=val2
      sampler:
        type: const
        param: 1
      propagation: JAEGER
      traceid-128bit: true
aws-config:
  dynamo-region: us-east-1
  table-name: CommentDB
  cognito-issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_cl8iVMzUw
